services:
  - type: web
    name: liff-drawing-search
    env: python
    plan: free
    buildCommand: python3 -c "import os; open('.render-rebuild-trigger', 'w').write(str(os.time()))"
    startCommand: python3 search_server.py
